# CSV file with single column, patient, with every patient ID
patients: patients.csv
# CSV file with info on each sample
units: units.csv

# Reference genome sources
# Directory where reference fasta and supporting files are stored
ref_dir: /home/groups/carilee/refs/hg38
# Name of reference FASTA (should be unzipped)
ref_fasta: Homo_sapiens_assembly38.fasta
# Comma separated names of VCF files with known mutations. 
# Should all be in the reference directory
known_sites: dbsnp_138.hg38.vcf.gz, Mills_and_1000G_gold_standard.indels.hg38.vcf.gz, resources-broad-hg38-v0-Homo_sapiens_assembly38.known_indels.vcf.gz
# BED file with exome regions that were targeted for capture. Doesn't have to be in ref_dir
exome_targets: /home/groups/carilee/refs/Twist_Exome_Target_hg38.bed
# AF only VCF with common allele frequencies - use gnomAD file
germline_resource: /home/groups/carilee/refs/gnomAD/af-only-gnomad.hg38.vcf.gz
# Biallelic variants only VCF with AF data - use EXAC file
contamination_resource: /home/groups/carilee/refs/gnomAD/small_exac_common_3.hg38.vcf.gz

# Annotation data sources
# Directory with VEP annotation data
vep_dir: /home/groups/carilee/refs/vep_data
# Reference fasta VEP should use for annotation
vep_fasta: /home/groups/carilee/refs/vep_data/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz 
# Assembly version name
assembly_version: GRCh38
# Value for Center field in the combined MAF
center_name: lee-lab

# Panel of Normal (PON)
# Use PON with Mutect2 for variant calling
use_pon: true
# Filepath for PON. To create a new PON from all the normal samples, specify as None
pon_vcf: None
# GATK, Picard, or BED style interval file with intervals to use for Panel of Normal Creation
interval_file: /home/groups/carilee/refs/hg38/wgs_calling_regions.hg38.interval_list
